spring:
  # mysql DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://d201.kro.kr:3121/eyeson?serverTimezone=Asia/Seoul
#    username: d201
#    password: ssafyd201
#    url: jdbc:mysql://d201.kro.kr:3121/eyeson?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/eyeson?serverTimezone=Asia/Seoul
    username: root
    password: hy1234
#  security:
#    google_id_token: [ ]
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            scope: profile, email
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB

  # jpa ??
  jpa:
    database: mysql
    show-sql: true  # jpa? hibernate? ?? CRUD? ???? ?? CRUD? sql? ???? ????
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # ?? ?? DB? ?? SQL ??? ??
    hibernate:
      ddl-auto: create  # ??? ??? ? ?? ??? ??? ??? ??
    properties:
      hibernate:
        format_sql: false  # ??? ???? sql? ?? ?? ???.


jwt:
  header: Authorization
  secret: dkssudgktpdywjsmsqogPdusdlqslekskdjqtsmsepvlrhsgkekekemfghkdddfsdflxldTkdTkdqkuZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQKeidltidj
  access-token-validity-in-seconds: 1800 # ? ??
  refresh-token-validity-in-seconds: 604800

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


