spring:
  # mysql DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(vN7xFvEM7j9CQP6frrxqaPBu5yafP1vKvG67MqSBB9n7OA6aetBIIv1dpALzwG7EaEYFbp5DhzCCIL6UUf6BeLBYm/ZsA1Q+)
    username: ENC(bm8ALWaol+28lr5SFL9k+r0dWkatllZa)
    password: ENC(AoNDyBW9+LV8Wfv9xD/hEA==)
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # jpa
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false


jwt:
  header: Authorization
  secret: ENC(5YbHygzTCGuhktBHhUXgzb/VBBVpsBsnA5UkxVElprfTopPyAOQDjlDOByAdeQNxgET2ew87k8aDx5Icg2mZzHhPVnirx/qpyQ5mf+GFd6VxjOj6Qj8xmsxeR4maK5J0BpmA/EJdOiGaGqktPSU2dj6r1lI+lGn+5Rbopikjknz7yrGAzRnwag==)
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt.encryptor.password}

server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true







